server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/limite
    hikari:
      username: limite
      password: limite_passwd
  flyway:
    baselineOnMigrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
    generate-ddl: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: limites-svc
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true

limite:
  valor: 2000

app:
  topic: transaction
  returnTopic: transaction_extorno